name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "adopt"
      - name: Build and Test
        run: sbt +test
      - name: Create release on tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
      - name: Update formula
        uses: "mislav/bump-homebrew-formula-action@v3"
        with:
          download-url: https://github.com/harehare/restui/releases/download/${{ steps.extract-version.outputs.tag-name }}/restui-${{ steps.extract-version.outputs.tag-name }}.tar.gz
          formula-name: restui
          homebrew-tap: harehare/homebrew-tap
